### ISSUE TITLE
Problems with Flutter version 

### ISSUE THREAD

**Issue by gT-mike** [AndriousSolutions/ads#2]
Hi,

in encountered the following problem trying to utilize the ads.git library: When I run 

```flutter.bat --no-color packages get``` 

I get the following error:

```
The current Dart SDK version is 2.1.0-dev.3.1.flutter-760a9690c2.

Because flutter_ad_screen depends on ads from git which requires SDK version <2.0.0, version solving failed.
pub get failed (1)
Process finished with exit code 1
```

It seems that the library is not compatible with newer flutter versions. Could that be fixed?

Further, I missed in the tutorial: What do I hav eto "import .." in the main.dart file so that the classes are available?

My pubspec.yaml looks like this (relevant part):

```
name: flutter_ad_screen
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^3.0.3
  ads:
   git:
    url: git://github.com/AndriousSolutions/ads.git

dev_dependencies:
  flutter_test:
    sdk: flutter
```

Many thanks in advance !! gT-Mike
